global:
  mock:
    service: "all"
  osb:
    instanceName: mushop
  ociAuthSecret:
  ossStreamSecret:
  oadbAdminSecret:
  oadbWalletSecret:
  oadbConnectionSecret:
  oosBucketSecret:

# Depending on the scenario, certain resources might need to be skipped.
# For example, --set skip.streaming=true to disable required streaming secrets
skip:
  streaming: false

ingress:
  enabled: true

api:
  enabled: true

assets:
  enabled: true

carts:
  enabled: true

catalogue:
  enabled: true

edge:
  enabled: true

orders:
  enabled: true

payment:
  enabled: true

session:
  enabled: true

shipping:
  enabled: true

storefront:
  enabled: true

stream:
  enabled: true

user:
  enabled: true

secrets:
  streams:
    region:
    compartmentId:
    streamName:
    streamId:
  bucket:
    region:
    name:
    namespace:
    par: